;SUB D,S  -->D-S 
;JNC-->JUMP NOT CARRY,  JC-JUMP CARRY 
;INC-+1 INCREASE
;NOT-BIT BY BIT COMPLIMENT
MOV AL, 11
MOV BL, 9
MOV CL,00
SUB AL,BL
JNC L1
INC CL
NOT AL
ADD AL,1
L1: MOV DS:[0301H],AL
     MOV DS:[0304H],CL
     HLT